name: franklab_mountainsort
channels:
- conda-forge
- flatiron
- defaults
- edeno
dependencies:
- mountainlab
- mountainlab_pytools
- ml_ephys
- ml_pyms
- ml_ms4alg
- ml_ms3
- qt-mountainview
- franklab_msdrift
- franklab_mstaggedcuration
- jupyter
- jupyterlab
- pandas
- dask
- "python >= 3.6"
